name: "General Issue"
description: Create a new ticket for issues not covered by other templates.
title: "[ISSUE] "
labels: [
  "question",
  "help wanted"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter a detailed description of the issue.
      placeholder: Short and explicit description of the issue...
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: "Context"
      description: Provide any additional context or information relevant to the issue.
      placeholder: Additional context or information...
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: "Steps to Reproduce"
      description: Describe the steps to reproduce the issue, if applicable.
      placeholder: Steps to reproduce the issue...
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      description: Describe what you expected to happen.
      placeholder: Expected behavior...
    validations:
      required: false
  - type: textarea
    id: actual
    attributes:
      label: "Actual Behavior"
      description: Describe what actually happened.
      placeholder: Actual behavior...
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: Add any other context or screenshots about the issue here.
      placeholder: Additional context or screenshots...
    validations:
      required: false
