name: "Feature Request"
description: Create a new ticket for a feature request.
title: "[FEATURE] "
labels: [
  "enhancement"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter a detailed description of the feature you would like to request.
      placeholder: Short and explicit description of the feature...
    validations:
      required: true
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: "Acceptance Criteria"
      description: Please provide the list of criterions for completing the issue.
      placeholder: 
    validations:
      required: true
  - type: textarea
    id: size
    attributes:
      label: "Size"
      description: The estimated time it will take to complete the issue.
      placeholder: Description of alternative solutions...
    validations:
      required: false
