name: "Feature Request"
description: Create a new ticket for a feature request.
title: "[FEATURE] "
labels: [
  "enhancement"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter a detailed description of the feature you would like to request.
      placeholder: Short and explicit description of the feature...
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: "Motivation"
      description: Please explain why this feature is important and how it will benefit the project.
      placeholder: Explanation of the motivation behind this feature request...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives"
      description: Please describe any alternative solutions or features you've considered.
      placeholder: Description of alternative solutions...
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: Add any other context or screenshots about the feature request here.
      placeholder: Additional context or screenshots...
    validations:
      required: false
